[build]
  command = "npm ci && npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express", "@supabase/supabase-js", "nodemailer"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api:splat"
  status = 200
